name: Deploy Azure Data Factory

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      AZURE_CLIENT_ID:
        required: true
        type: string
      AZURE_CLIENT_SECRET:
        required: true
        type: string
      AZURE_SUBSCRIPTION_ID:
        required: true
        type: string
      AZURE_TENANT_ID:
        required: true
        type: string

env: 
  adfName: $(jq -r ".adfName" ./bicep/parameters/${{ inputs.environment }}Parameters.json)
  resourceGroupName: $(jq -r ".resourceGroupName" ./bicep/parameters/${{ inputs.environment }}Parameters.json)

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: echo ${{env.adfName}}
           echo ${{env.resourceGroupName}}

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true

    # - name: Read linkedService JSON files and deploy
    #   run: |
    #       az deployment group create \
    #         --resource-group "komatsu" \
    #         --template-file ./bicep/modules/dataFactory.bicep \
    #         --parameters dataFactoryName="WithoutJson" \
    #         --parameters keyVaultName="${{env.keyVaultName}}" \
    #         --parameters blobStorageSecretName="${{env.connectionSecretName}}" \
            