name: Deploy ADF LinkedService

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

env: 
  keyVaultName: 'kx1-demo-dev'
  connectionSecretName: 'kx-demo-constring-dev'
  credentialSecretName: 'kx-demo-cred-dev'

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Check Secrets
      run: |
           echo '${{ secrets.AZURE_CLIENT_ID }}'
           echo ${{secrets.AZURE_CLIENT_SECRET}}
           echo ${{secrets.AZURE_SUBSCRIPTION_ID}}
           echo ${{secrets.AZURE_TENANT_ID}}

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true

    - name: Read Linked Service Dependencies
      run: |
          echo "LINKED_SERVICES_DEPENDENCIES=$(cat linkedServicesDependencies.json)" >> $GITHUB_ENV

    - name: Deploy Linked Services in Order
      run: |
        linked_services='${{ env.LINKED_SERVICES_DEPENDENCIES }}'
        deployed=()

        deploy_linked_service() {
          local linked_service=$1
          if [[ " ${deployed[@]} " =~ " $linked_service " ]]; then
            echo "$linked_service already deployed."
            return
          fi
          # Deploy dependencies first
          for dep in $(echo $linked_services | jq -r ".[\"$linked_service\"][]"); do
            deploy_linked_service $dep
          done
          echo "Deploying Linked Service: $linked_service..."
          az datafactory linked-service create --factory-name komatsu-test-poc --resource-group komatsu-poc \
            --template-file ./bicep/modules/linkedService.bicep  "linkedService/$linked_service.json"
          deployed+=("$linked_service")
        }

        for linked_service in $(echo $linked_services | jq -r 'keys[]'); do
          deploy_linked_service $linked_service
        done
          