name: Deploy ADF Components

on:
  push:
    branches:
      - 'feature-*'
    tags:
      - 'v*'

jobs: 
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: |
  #         npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

  #     - name: Run semantic-release
  #       run: |
  #         npx semantic-release
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get the most recent tag
        id: get_tag
        run: |
            LAST_TAG=git describe --tags --abbrev=0
            echo "Last tag: $LAST_TAG"
            echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
  
      - name: Increment version
        run: |
            VERSION=${LAST_TAG#v}
            MAJOR=$(echo $VERSION | cut -d '.' -f 1)
            MINOR=$(echo $VERSION | cut -d '.' -f 2)
            PATCH=$(echo $VERSION | cut -d '.' -f 3)
  
            PATCH=$((PATCH + 1))  # Increment the patch version by 1
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
  
            echo "New version: $NEW_VERSION"
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
  
      - name: Create and push new tag
        run: |
            git config --global user.email "dmj571999@gmail.com"  # Set your Git email
            git config --global user.name "DMJ57"  # Set your Git username
  
            # Create an annotated tag
            git tag -a $NEW_VERSION -m "Release version $NEW_VERSION"
  
            # Push the new tag to GitHub
            git push origin $NEW_VERSION

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: |
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }

  # deploy-GlobalParameters:
  #   needs: build
  #   uses: ./.github/workflows/Factory.yml
  #   with: 
  #     branch: feature-ADF-code
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-LinkedService:
  #   needs: deploy-GlobalParameters
  #   uses: ./.github/workflows/LinkedService.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-DataSets:
  #   needs: deploy-LinkedService
  #   uses: ./.github/workflows/DataSets.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-DataFlow:
  #   needs: deploy-DataSets
  #   uses: ./.github/workflows/DataFlow.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-Pipeline:
  #   needs: deploy-DataFlow
  #   uses: ./.github/workflows/Pipeline.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
  # deploy-Trigger:
  #   needs: deploy-Pipeline
  #   uses: ./.github/workflows/Trigger.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

