on:
  push:
    branches:
      - 'feature-*'
    tags:
      - 'v*'


jobs: 

  read-secrets:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read secrets
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "environment=Dev" >> $GITHUB_ENV

  dispaly-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Display Secrets
        run: |
          echo $AZURE_CLIENT_ID
          echo $AZURE_CLIENT_SECRET
          echo $AZURE_SUBSCRIPTION_ID
          echo $AZURE_TENANT_ID
          echo $environment

  Deploy-Data-Factory:
        uses: ./.github/workflows/dataFactory.yml
        with:
          environment: $environment
          AZURE_CLIENT_ID: $AZURE_CLIENT_ID
          AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
          AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID
          AZURE_TENANT_ID: $AZURE_TENANT_ID

  # deploy-LinkedService:
  #   needs: build
  #   uses: ./.github/workflows/LinkedService.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}