name: Deploy ADF Components

on:
  push:
    branches:
      - 'feature-*'
    tags:
      - 'v*'

env:
  environment: Dev

jobs: 
  
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Log in to Azure
  #       uses: azure/login@v2
  #       with:
  #         creds: |
  #             {
  #               "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
  #               "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
  #               "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
  #               "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
  #             }
  
              
  deploy-ADF:
    uses: ./.github/workflows/dataFactory.yml
    with: 
      branch: feature-ADF-code
      environment: ${{ github.env }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-LinkedService:
  #   needs: build
  #   uses: ./.github/workflows/LinkedService.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-DataSets:
  #   needs: deploy-LinkedService
  #   uses: ./.github/workflows/DataSets.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-DataFlow:
  #   needs: deploy-DataSets
  #   uses: ./.github/workflows/DataFlow.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # deploy-Pipeline:
  #   needs: deploy-DataFlow
  #   uses: ./.github/workflows/Pipeline.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
  # deploy-Trigger:
  #   needs: deploy-Pipeline
  #   uses: ./.github/workflows/Trigger.yml
  #   with: 
  #     branch: 'feature-*'
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      