name: Deploy ADF Pipelines

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true  # Make sure to store your Azure credentials as secrets

    - name: Read pipeline JSON files and deploy
      run: |
        # Ensure the correct path to the JSON files
        pipeline1=$(cat ./pipeline/pipeline.json)

        # Construct a JSON array with the pipeline contents
        pipelines=$(jq -n \
          --arg pipeline1 "$pipeline1" \
          '[
            {
              "name": "pipelinePOC",
              "definition": $pipeline1 | fromjson
            }
          ]')

        # Deploy using Bicep (or ARM template)
        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/modules/pipeline.bicep \
          --parameters dataFactoryName=PresentationPOC \
          --parameters pipelines="$pipelines"